import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Spotlight } from "@/components/ui/spotlight-new";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black/[0.96] text-white min-h-screen`}
      >
        <div className="fixed inset-0 w-full h-full bg-grid-white/[0.02] pointer-events-none z-0 overflow-hidden">
          <Spotlight />
        </div>
        <div className="relative z-10">{children}</div>
      </body>
    </html>
  );
}
